#!/usr/bin/env python3
"""
create_project.py – Create a new GitHub repository from the saas-template.

Uses GitHub's template-repository generation endpoint so the new repo is
pre-populated with the contents of the factory template.

Usage:
    python scripts/create_project.py --project-id my-saas --org myorg [--dry-run]

Environment variables required (unless --dry-run):
    GITHUB_TOKEN    – personal access token with repo creation rights
    TEMPLATE_OWNER  – owner of the template repo (default: ismaelloveexcel)
    TEMPLATE_REPO   – name of the template repo  (default: ai-dan-factory)
"""

import argparse
import json
import os
import sys
import urllib.error
import urllib.request


def _github_request(method: str, path: str, payload: dict | None = None, token: str = "") -> dict:
    url = f"https://api.github.com{path}"
    data = json.dumps(payload).encode() if payload else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    if data:
        req.add_header("Content-Type", "application/json")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as exc:
        body = exc.read().decode()
        print(f"[error] GitHub API {method} {url} → HTTP {exc.code}: {body}", file=sys.stderr)
        raise


def create_repo(
    project_id: str,
    org: str,
    token: str,
    template_owner: str,
    template_repo: str,
    private: bool = True,
) -> dict:
    """Generate a new repository from the template under *org* named *project_id*."""
    payload = {
        "owner": org if org else None,
        "name": project_id,
        "private": private,
        "description": f"Generated by ai-dan-factory for project {project_id}",
    }
    # Remove None values so GitHub doesn't reject them
    payload = {k: v for k, v in payload.items() if v is not None}
    return _github_request(
        "POST",
        f"/repos/{template_owner}/{template_repo}/generate",
        payload=payload,
        token=token,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a GitHub repo for a new SaaS project")
    parser.add_argument("--project-id", required=True, help="Repository / project name")
    parser.add_argument("--org", default="", help="GitHub organisation (leave blank for personal account)")
    parser.add_argument("--public", action="store_true", help="Create a public repository")
    parser.add_argument("--dry-run", action="store_true", help="Print what would happen without calling GitHub")
    args = parser.parse_args()

    token = os.environ.get("GITHUB_TOKEN", "")
    template_owner = os.environ.get("TEMPLATE_OWNER", "ismaelloveexcel")
    template_repo = os.environ.get("TEMPLATE_REPO", "ai-dan-factory")

    if args.dry_run:
        owner = args.org or "<your-github-user>"
        print(
            f"[dry-run] Would generate repo: {owner}/{args.project_id} "
            f"from {template_owner}/{template_repo} (private={not args.public})"
        )
        return

    if not token:
        sys.exit("[error] GITHUB_TOKEN environment variable is not set.")

    result = create_repo(
        project_id=args.project_id,
        org=args.org,
        token=token,
        template_owner=template_owner,
        template_repo=template_repo,
        private=not args.public,
    )
    print(f"[ok] Repository created: {result['html_url']}")


if __name__ == "__main__":
    main()
