#!/usr/bin/env python3
"""
Create a GitHub repository from a template repository.

Required environment variables (unless --dry-run):
  - GITHUB_TOKEN

Optional environment variables:
  - TEMPLATE_OWNER
  - TEMPLATE_REPO
  - GITHUB_REPOSITORY (owner/repo fallback for template source)
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request


def _resolve_template_defaults() -> tuple[str, str]:
    owner = os.environ.get("TEMPLATE_OWNER", "").strip()
    repo = os.environ.get("TEMPLATE_REPO", "").strip()
    if owner and repo:
        return owner, repo

    current_repo = os.environ.get("GITHUB_REPOSITORY", "").strip()
    if "/" in current_repo:
        fallback_owner, fallback_repo = current_repo.split("/", 1)
        return owner or fallback_owner, repo or fallback_repo

    return owner, repo


def _github_request(method: str, path: str, token: str, payload: dict[str, object]) -> dict[str, object]:
    url = f"https://api.github.com{path}"
    body = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(url=url, data=body, method=method)
    request.add_header("Accept", "application/vnd.github+json")
    request.add_header("X-GitHub-Api-Version", "2022-11-28")
    request.add_header("Content-Type", "application/json")
    request.add_header("Authorization", f"Bearer {token}")

    try:
        with urllib.request.urlopen(request) as response:
            raw = response.read().decode("utf-8")
            return json.loads(raw) if raw else {}
    except urllib.error.HTTPError as exc:
        error_body = exc.read().decode("utf-8", errors="replace")
        raise SystemExit(f"[error] GitHub API request failed ({exc.code}): {error_body}") from exc


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a GitHub repository from a template repository")
    parser.add_argument("--project-id", required=True, help="Repository slug to create (example: acme-saas)")
    parser.add_argument("--org", default="", help="GitHub org/user that will own the repository")
    parser.add_argument("--template-owner", default="", help="Template repository owner")
    parser.add_argument("--template-repo", default="", help="Template repository name")
    parser.add_argument("--public", action="store_true", help="Create a public repository (default: private)")
    parser.add_argument("--dry-run", action="store_true", help="Validate inputs and print intended action")
    args = parser.parse_args()

    if not re.fullmatch(r"[A-Za-z0-9._-]+", args.project_id):
        raise SystemExit("[error] --project-id must match [A-Za-z0-9._-]+")

    default_template_owner, default_template_repo = _resolve_template_defaults()
    template_owner = (args.template_owner or default_template_owner).strip()
    template_repo = (args.template_repo or default_template_repo).strip()
    if not template_owner or not template_repo:
        raise SystemExit(
            "[error] Template repository is not configured. "
            "Set TEMPLATE_OWNER and TEMPLATE_REPO (or pass --template-owner/--template-repo)."
        )

    target_owner = args.org.strip() or "<current-authenticated-user>"
    visibility = "public" if args.public else "private"

    if args.dry_run:
        print(
            f"[dry-run] Would create {target_owner}/{args.project_id} "
            f"from template {template_owner}/{template_repo} ({visibility})"
        )
        return

    token = os.environ.get("GITHUB_TOKEN", "").strip()
    if not token:
        raise SystemExit("[error] GITHUB_TOKEN is required.")

    payload: dict[str, object] = {
        "name": args.project_id,
        "private": not args.public,
        "description": f"Generated by GitHub Factory for project {args.project_id}",
        "include_all_branches": False,
    }
    if args.org.strip():
        payload["owner"] = args.org.strip()

    result = _github_request(
        method="POST",
        path=f"/repos/{template_owner}/{template_repo}/generate",
        token=token,
        payload=payload,
    )
    repo_url = str(result.get("html_url", ""))
    if not repo_url:
        raise SystemExit("[error] GitHub API did not return repository URL.")
    print(f"[ok] Repository created: {repo_url}")


if __name__ == "__main__":
    main()
